services:
  mongo.db.catalog:
    restart: always
    image: mongo:8.0-rc
    container_name: mongo.db.catalog.container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27030:27017"
    volumes:
      - mongo.db.catalog.volume:/data/db
    networks:
      default:
        aliases:
          - mongo

  mongo.db.catalog.ui:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo_db_catalog_ui
    ports:
      - "27032:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo.db.catalog.volume:
